### ISSUE TITLE
add speaker - Ping Chen + tomo 

### ISSUE THREAD

**Issue by KimiWu123** [ETHTaipei/ETH-Taipei-Website#133]
Ping Chen - Hakka Finance
  - twitter: https://twitter.com/PingChenTW
  - pfp: https://drive.google.com/file/d/1jw_hu5hJl-ly4hhwNWaoY4UGrKjCU5Hm/view?usp=share_link

**Comment by antoncoding** [comment]
also missing speaker Tomo Tagami, Pheasant Network from the home page

**Comment by KimiWu123** [comment]
Tomo Tagami - Pheasant Network
- twitter: https://twitter.com/tomohiro_tagami
- pfp: https://drive.google.com/file/d/1Za2wCA9BJIJedi6a929jUf7a17cqzhc4/view?usp=share_link
