### ISSUE TITLE
Agenda Update

### ISSUE THREAD

**Issue by KimiWu123** [ETHTaipei/ETH-Taipei-Website#146]
### AGENDA
- Add opening at 9:50am
- keynote speaker starts at 10:00am
- DEFI DAY1
  - Tom Soong (10:30 Zomma Protocol)
     - Speaker: change to `Charlotte` 
- DEFI DAY2
   - Ping Chen
      - Topic: Playing with Ethereum, the map editor of electronic cash
- ZK/Client DAY2
   - Richard Ma, Quantstamp (2:30pm)
      - Topic: The Impact of Chain Forks and Reorgs on Cross-chain Bridges
      - Speaker: change to `Poming Lee`
 
### SPEAKERS
- remove Tom Soong 
- add Poming Lee
- add Charlotte

**Comment by antoncoding** [comment]
* add topic for Ping: "Playing with Ethereum, the map editor of electronic cash"

**Comment by martinetlee** [comment]
![image](https://user-images.githubusercontent.com/32376541/233300111-793bff41-9e9a-4695-b96e-d3caa4246998.png)


Poming's avatar

**Comment by martinetlee** [comment]
![telegram-cloud-photo-size-5-6199641818849719628-y](https://user-images.githubusercontent.com/32376541/233301398-dbe0aec0-f410-4955-b2e8-5993d4478c4c.jpg)

**Comment by AnnieChi1020** [comment]
Charlotte & Poming 有要放 twitter link 嗎
