### ISSUE TITLE
下架講者

### ISSUE THREAD

**Issue by KimiWu123** [ETHTaipei/ETH-Taipei-Website#150]
- 把 Tom Soong 從講者名單移除
- Agenda update
  - DEFI DAY1 10:30 Zomma Protocol
     - 講者從 Tom Soong 換成 Charlotte

**Comment by martinetlee** [comment]
* Agenda update
  * DEFI DAY2 02:30 pm  TBD =>  The Impact of Chain Forks and Reorgs on Cross-chain Bridges , speaker => Poming Lee
* Add Speaker 
  * Poming Lee

(no need to remove Richard Ma as he will join as security panelist. I will add the info of panelist in a bit as a separate issue)

**Comment by KimiWu123** [comment]
merged to #146
