### ISSUE TITLE
保留 2023 資料在新的頁面

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#176]
# Description

將目前網站資料保留在一個 subdomain or 特定 URL

**Comment by Ankarrr** [comment]
我認爲 #178 #179 應該和這個票有關，屬於要被保留得資料

**Comment by antoncoding** [comment]
目前先放在這裡，等待設定好 subdomain 再來連線：https://ethtaipei-2023.netlify.app/agenda

**Comment by Ankarrr** [comment]
https://2023.ethtaipei.org/
