### ISSUE TITLE
Martinet's feedback

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#183]
剛剛在看整個網站時，想到幾個建議：
1) 2024 版本多加一個選項連到 2023 
2) 2023 版本上面多加一個連回 2024，然後讓 這是舊版本這件事情很明顯 (not sure how)
3) Speaker application 的按鈕可以移到最上面嗎？在下面好遠，最好是一打開網頁直接看到，要不就是馬上 scroll 就找到
4) 可以加上 Sponsorship application的按鈕然後也跟. Speaker application的按鈕放在一起在最上面嗎？
5) 我們的說明文要改了，不是 first ETHTaipei 了XD 
       a) "Welcome to the first ETHTaipei held in Taiwan." ==> "Welcome to ETHTaipei the 2024 edition!!!"
       b) "We believe that ETHTaipei presents an unparalleled opportunity to learn about cutting-edge technology and applications about Ethereum" => "ETHTaipei presents an unparalleled opportunity to learn about cutting-edge technology and applications about Ethereum (check out our 2023 edition here!)" 然後把 here 連結到 2023版本的 agenda

**Comment by DylanYang0523** [comment]
hi @Ankarrr
