### ISSUE TITLE
上線 ticket sites / hackathon sites / side event sites

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#186]
Todo 
- [x] ticket sites: https://app.moongate.id/e/eth-taipei
- [x] hackathon sites
- [x] side event sites

**Comment by Ankarrr** [comment]
這個票需要等外部網站設定好，就我所知還沒 ready，所以先放著

**Comment by martinetlee** [comment]
Ticket sites: https://app.moongate.id/e/eth-taipei
Hackathon site: https://taikai.network/ethtaipei/hackathons/hackathon-2024

thanks!!!
