### ISSUE TITLE
網頁 UIUX Re-design

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#205]
根據年前的討論

基於 Danny 目前的設計，還有一些 feedback:
- Landing page 內容部分佔比降低、slogan 拿掉
- CTA buttons 調整為最重要的 Ticket、Hackathon、Speaker
- Navbar buttons 調整為 Ticket、Hackathon、Apply（點擊後有 drop-down）
- Sponsor 要分 Tier、加上 Title

**Comment by DylanYang0523** [comment]
https://github.com/ETHTaipei/ETH-Taipei-Website/tree/feature/redesign
