### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#23]
# Description

<img width="939" alt="截圖 2023-02-25 下午11 26 24" src="https://user-images.githubusercontent.com/8311552/221365341-5d9e8d62-c010-40a4-902f-f8eba71701f7.png">

使用 google analytics

# Todo
- [x] 設定 GA

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-TT1QEL839P"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-TT1QEL839P');
</script>
```

**Comment by Ankarrr** [comment]
@AnnieChi1020 有空麻煩幫忙設定 🙏

**Comment by AnnieChi1020** [comment]
已加

<img width="582" alt="Screen Shot 2023-03-01 at 5 23 41 PM" src="https://user-images.githubusercontent.com/77234273/222097443-fc712e3e-11dd-4f7e-af74-ff10e132a85d.png">
