### ISSUE TITLE
Add speakers on agenda

### ISSUE THREAD

**Issue by Ankarrr** [ETHTaipei/ETH-Taipei-Website#65]
# Description

Agenda 目前有一個草稿，希望先把確定的講者、公司按照日期放到官網上

### April 24

DeFi Track
- Daniele Ugolini, Rysk Finance
- Deyeon Kim, Pods Finance
- Ibe, Predy Finance
- Gauthem, Polynomial
- Tom soong, Zomma
- Jake, Gauntlet 
- Zac L, Suberra
- Anderson Chen, Diamond Protocol

ZK / L2 / Client Track
- Hsiao-Wei Wang, Ethereum Foundation
- Dapplion, ChainSafe
- Jobin Babu Ayathil, Obscuro
- I-Hung Hsu, AMIS
- Vivian, Ethereum Foundation
- Cathie, Ethereum Foundation
- Balal Khan, ZKEX
- Chris Tam, BTQ
- Nuno Loureiro, Ethereum Foundation

### April 25

DeFi Track
- Yenwen, Perpetual Protocol
- ZD Hu, Furucombo
- Martinet, Quantstamp
- Marry Lui, Celestia

ZK / L2 / Client Track
- Wanseob Lim, Ethereum Foundation
- Nic, imToken
- Shotaro Granzier-Nakajima, Kleros
- Savio, Aztec
- Guiltygyoza, Topology
- Alfred, imToken
- Guru, Status

**Comment by KimiWu123** [comment]
> Cathie, Ethereum Foundation
He is not EFer, he is grantee at EF. It's fine to keep blank.
